# Generated by Django 5.2.1 on 2025-06-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_empty_bottle_alter_item_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category name:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='Category:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per unit:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='empty_bottle',
            field=models.FloatField(blank=True, null=True, verbose_name='Empty bottle weight:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item name:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Units:'),
        ),
    ]
