# Generated by Django 5.2.1 on 2025-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_name_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(choices=[('300 ml', '300 ml'), ('750 ml', '750 ml'), ('1000 ml', '1000 ml'), ('bottle', 'bottle'), ('units', 'units')], default='bottle', max_length=20, verbose_name='Units:'),
        ),
    ]
