# Generated by Django 5.2.1 on 2025-06-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_quantity_alter_item_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(choices=[('300 ml', '300 ml'), ('750 ml', '750 ml'), ('1000 ml', '1000 ml'), ('bottle', 'bottle'), ('units', 'units')], max_length=20, verbose_name='Units:'),
        ),
    ]
